<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro" />


    <xacro:property name="chassis_length" value="2.01" />
    <xacro:property name="chassis_width" value="1.07" />
    <xacro:property name="chassis_height" value="0.2" />
    <xacro:property name="chassis_mass" value="1.0" />
    <xacro:property name="wheel_radius" value="0.18" />
    <xacro:property name="wheel_thickness" value="0.026" />
    <xacro:property name="wheel_mass" value="0.05" />
    <xacro:property name="wheel_offset_x" value="0.226" />
    <xacro:property name="wheel_offset_y" value="0.312" /> <!-- ? Important-->
    <xacro:property name="wheel_offset_z" value="-0.1" />
    <xacro:property name="caster_wheel_radius" value="0.18" />
    <xacro:property name="caster_wheel_mass" value="0.01" />
    <xacro:property name="caster_wheel_offset_x" value="${chassis_length - 0.45}" />
    <xacro:property name="caster_wheel_offset_z"
        value="${- wheel_radius + caster_wheel_radius + wheel_offset_z}" />

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1" />
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1" />
    </material>

    <material name="black">
        <color rgba="0 0 0 1" />
    </material>

    <material name="red">
        <color rgba="1 0 0 1" />
    </material>

    <!-- ? Empty Visual  -->
    <xacro:macro name="empty_visual" params="*origin">
        <visual>
            <xacro:insert_block name="origin" />
            <geometry>
                <box size="0 0 0" />
            </geometry>
            <material
                name="">
                <color rgba="1 1 1 0.4" />
            </material>
        </visual>
    </xacro:macro>


    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_footprint">
    </link>

    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="0 0 0" rpy="${pi} 0 0" />
    </joint>

    <link name="chassis">
        <xacro:empty_visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:empty_visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}"
            z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <!-- LEFT WHEEL LINK -->

    <joint name="Joint_Left_Fan" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <origin xyz="0.3 ${wheel_offset_y} ${wheel_offset_z}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="left_wheel">
        <xacro:visual_fan>
            <origin xyz="0 0 0" rpy="-${pi/2} 0 0" />
        </xacro:visual_fan>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
            radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="left_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>


    <!-- RIGHT WHEEL LINK -->

    <joint name="Joint_Right_Fan" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin xyz="0.3 ${-wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1" />
    </joint>

    <link name="right_wheel">
        <xacro:visual_fan>
            <origin xyz="0 0 0" rpy="-${pi/2} 0 0" />
        </xacro:visual_fan>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
            radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>


    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel" />
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}" />
    </joint>


    <link name="caster_wheel">
        <xacro:empty_visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:empty_visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001" />
        <mu2 value="0.001" />
    </gazebo>

</robot>